### ISSUE TITLE
Cant install windown 7?

### ISSUE THREAD

**Issue by Thermalzombie** [suratovvlad/qbittorrent-installer#11]
Hi just tried to install on windows 7 and get the below error.

 Error: Cannot write maintenance tool data to C:/users/username/appdata/local/temp/qbittorrentdarkinstaller-4.ftbwdc: unknown error

Also the installer is installing to the 64bit program files folder not sure it this is the 64bit version or not and I do have the standard 64bit qbittorrent installed.

Was looking forward to this hopefully a simple fix.

**Comment by Thermalzombie** [comment]
Solved running installer as administrator fixes the issue.

Thanks for the dark theme really appreciate it.

**Comment by suratovvlad** [comment]
Yes, there is a problems with admin rights insider the qt installer framework.

Another solution is to install to the folder with your user access
