### ISSUE TITLE
Add option for previous Dark Theme

### ISSUE THREAD

**Issue by araujojr82** [suratovvlad/qbittorrent-installer#15]
The previous theme was better than the one by libqdark. Is there a way to add it to the next releases?

**Comment by suratovvlad** [comment]
I'm thinking about it about two years, since original stylesheet has been changed, however I've only created an issue for [libqdark](https://github.com/suratovvlad/libqdark/issues/4) and did nothing.

**Comment by XFGibson** [comment]
In the dark mode the names of the torrents, written in dark blue on a black background, are almost unreadable
![изображение](https://user-images.githubusercontent.com/1096336/57179280-b3099980-6e84-11e9-8c37-cb7e7dae9957.png)

**Comment by JKotem** [comment]
Voting for original 'unplugged' DARK theme to be back - it's awesome.

**Comment by Soitora** [comment]
A dark theme similiar to that of normal dark grey applications (such as new dark explorer, spotify, discord, google apps etc) would be much prefered over a dark-blue theme

**Edit:**
Also, a colored titlebar would be awesome too so it's not 100% white.

```csharp
"titleBar.activeBackground": "#19232d",
"titleBar.activeForeground": "#cccccc",
"titleBar.inactiveBackground": "#32414b",
"titleBar.inactiveForeground": "#ffffff"
```

**Comment by suratovvlad** [comment]
https://github.com/suratovvlad/qbittorrent-installer/releases/tag/4.1.6

I published test version of libqdark.dll 
Please, try this one, what do you think?

You need just replace original from installation folder

**Comment by tiagop717** [comment]
I appreciate the work you put in this project, but the new dark mode on 4.1.6 just sucks.
The one being used on 4.1.5 is really nice, not sure why it was changed.
I tried replacing the .ddl file you added and although it's a bit better, it's way too hard to read any completed and seeding torrents with the colors being used.

Please just go back to the color setting being used on 4.1.5.
Thank you.

**Comment by Soitora** [comment]
Yeah, 4.1.5 had a much better dark theme, but please add titleBar colors.
Also, you're very close to the Windows 10 1809 Dark Explorer colors, would be nice if those could match

**Comment by suratovvlad** [comment]
>The previous theme was better than the one by libqdark. Is there a way to add it to the next releases?

>A dark theme similiar to that of normal dark grey applications (such as new dark explorer, spotify, discord, google apps etc) would be much prefered over a dark-blue theme

>Please just go back to the color setting being used on 4.1.5.

>new dark mode on 4.1.6 just sucks.

>Yeah, 4.1.5 had a much better dark theme

I added an option to use old styles in new release. 

>In the dark mode the names of the torrents, written in dark blue on a black background, are almost unreadable

>it's way too hard to read any completed and seeding torrents with the colors being used.

This is another issue, I have fixed in the way it was done in previous releases.


@Soitora 
>Also, a colored titlebar would be awesome too so it's not 100% white.
>but please add titleBar colors.

I'm not sure what are you talking about... Could you please create a ticket with more explanation?

**Comment by JKotem** [comment]
Thanks for adding 'old' dark theme.
