### ISSUE TITLE
v.4.1.5 reverts original theme

### ISSUE THREAD

**Issue by THGhost** [suratovvlad/qbittorrent-installer#16]
Every time I load up v4.1.5 of qBittorrentdark, it reverts back to the original theme. It also kept asking for an update which doesn't exist but disabling "check for updates" fixes that.

**Comment by suratovvlad** [comment]
The original v4.1.6 was released yesterday, so it says about new update.
No fixes to original code were applied, only dark theme in my version.

As for original theme reverting, it seems as an issue. Could you check please
`%LOCALAPPDATA%\qBittorrent\qdarktheme.conf`? Does it exist?

**Comment by THGhost** [comment]
4.1.5 was the latest version that I saw with "suratovvlad released this 3 days ago". I see 4.1.6 now with "9 minutes ago" :P

Installed 4.1.6 now. I couldn't find qdarktheme.conf on 4.1.5 and not on 4.1.6 either in local app data. The reverting theme issue appears to have gone away with 4.1.6 though.

I think I prefer the older dark theme, the newer one is nice too though. Any chance we could have the choice of both?

**Comment by suratovvlad** [comment]
>I think I prefer the older dark theme, the newer one is nice too though. Any chance we could have the choice of both?

I've already working on it, look at #15. It is almost ready, I just need to polish some things and more time for that.

> The reverting theme issue appears to have gone away with 4.1.6 though.

It's quite interesting :) Well, lets assume it is OK.

> I couldn't find qdarktheme.conf on 4.1.5 and not on 4.1.6 either in local app data.

It will be fixed btw.
