### ISSUE TITLE
Crash while installing dark4.1.6 Stable

### ISSUE THREAD

**Issue by alammahbub** [suratovvlad/qbittorrent-installer#17]
Crash while installing dark4.1.6 Stable
![Annotation 2019-05-08 230703](https://user-images.githubusercontent.com/9821810/57393945-0877da80-71e6-11e9-975a-688116a59718.jpg)

**Comment by suratovvlad** [comment]
Run as admin, or don't choose c:/program files. It's bug in Qt installer framework

**Comment by alammahbub** [comment]
Thanks, I did run as admin and It works.
