### ISSUE TITLE
Update to latest qbittorrent?!

### ISSUE THREAD

**Issue by EC-O-DE** [suratovvlad/qbittorrent-installer#2]
Dark theme/GUI/coloring is a must for Windows version!

**Comment by van-ess0** [comment]
I've tried to merge the latest version with this dark fork and, after several hours of conflicts resolving, gave up.
AFAIK @suratovvlad is busy ATM, so feel free to contribute :)

**Comment by suratovvlad** [comment]
Well, I've reverted master and updated to the upstream.
Also, I've created separate branch 'dark_theme' with old cherry-picked modifications.

The next step is to build it for windows and update AUR package. I hope I'll get the time for it for the next several weeks

**Comment by suratovvlad** [comment]
Done.

**Comment by suratovvlad** [comment]
It seems icons are broken, I don't know why exactly the reason, I will investigate it.
Also, it is suppose to be installed not in C:\Program Files\ directory, neither to any admin folder - this is Qt Installer Framework restriction, I didn't find a solution yet...

P.S. I'm totally drunk, however, I'm able to write responses yet :)
