### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by sclient** [suratovvlad/qbittorrent-installer#21]
For some reason when I uninstalled the original copy of QBT, now dark refuses to launch. I decided to upgrade to the latest version, but every attempt ends with this error and it reverses the install attempt.

Windows 8.1

**Comment by sclient** [comment]
Well for some reason the image I tried to attach.. Didnt.. And clicking the edit button also fails, so lets try again.

https://imgur.com/NOclwbS

**Comment by Thermalzombie** [comment]
I don't no for sure but when I first installed the dark version it carried over my settings from the standard release of qbittorrent light version.  Maybe when you uninstalled it removed some shared files.

I currently have both installed qbittorrent dark 4.1.5 and qbittorrent light 4.1.6 installed.

**Comment by suratovvlad** [comment]
Duplication #17
