### ISSUE TITLE
x64 build

### ISSUE THREAD

**Issue by hooddy** [suratovvlad/qbittorrent-installer#25]
Please make x64 build. Если честно, я вообще с удивлением обнаружил, что с темной темой сторонний форк, а в оригинале нет выбора тем.

**Comment by suratovvlad** [comment]
it is x64 already, I don't support x86, I described the reason of Program Files directory here #24.
Будет, сейчас там идут работы, раньше ментейнеры были максимально против моего пулреквеста, поэтому пришлось оставить форком и пилить свои инсталлер и пакеты.
Можете глянуть там историю, если интересно, по поиску dark в ишью их основной репы
