### ISSUE TITLE
Most Icons are missing, W10.

### ISSUE THREAD

**Issue by ghost** [suratovvlad/qbittorrent-installer#3]
The only icon I can see is the throttle icon

**Comment by van-ess0** [comment]
https://github.com/suratovvlad/qbittorrent-installer/issues/2#issuecomment-451338567

**Comment by suratovvlad** [comment]
It seems I've found the solution.
You just need to put these two folders in to the installation folder, e.g. D:\Program Files\qBittorrent-dark, from this archive
[fix_icons.zip](https://github.com/suratovvlad/qbittorrent-installer/files/2768798/fix_icons.zip)
Like this
![image](https://user-images.githubusercontent.com/3812290/51321845-ea3e7100-1a74-11e9-834b-ec6bca511fc6.png)

And then restart the application.

In the next release I will put them to the installer

**Comment by suratovvlad** [comment]
> The only icon I can see is the throttle icon

Could you please test the solution?

**Comment by suratovvlad** [comment]
New release with fixed icons is ready

**Comment by ghost** [comment]
Sorry I'm not all that active and the issue didn't bother me terribly, I simply went back to normal qB.
Now I have tested it, still in Program Files, and it works. Thanks :)
