### ISSUE TITLE
Why is the installer 80 MB?

### ISSUE THREAD

**Issue by oogba71** [suratovvlad/qbittorrent-installer#9]
The qBittorrent installer in just over 22 MB...

**Comment by suratovvlad** [comment]
The main reason is that original qBittorrent is build with Visual Studio with static mode, and doesn't require take all libraries along with the executable file.

I build qBittorrent with the MSYS2 tool with shared mode, so it requires get not only Qt*.dll with the executable, but also all stuff from MSYS2 layer such as libstdc++-6.dll and libwinpthread-1.dll

Another reason, I guess, that original installer, which is based on NSIS (Nullsoft Scriptable Install System), requires much less space inside installer than qifw (Qt Installer Framework) in my case.

**Comment by suratovvlad** [comment]
Wow there, I have found an issue, installer will become smaller later.
News https://blog.qt.io/blog/2019/05/17/qt-installer-framework-3-1-1-released/
Here is the original bug, https://bugreports.qt.io/browse/QTIFW-1322
